### ISSUE TITLE
customRomajiMapping works differently from WanaKana, is undocumented, unintuitive, and basically useless

### ISSUE THREAD

**Issue by BlueRaja** [caguiclajmg/WanaKanaSharp#6]
As a workaround to #5, I attempted this:

```
var bugfixTrie = new Trie<char, string>();
bugfixTrie.Root.Add('ふ', "fu");
bugfixTrie.Root.Add('フ', "fu");
var pronunciation = WanaKana.ToRomaji(japaneseWord, customRomajiMapping: bugfixTrie);
```

This has two problems:
* Most importantly, **it doesn't work**.  Apparently the `customRomajiMapping` overwrites the _entire_ mapping, meaning _only_ those two items will get translated. This means the `customRomajiMapping` parameter is unintuitive, works differently from original WanaKana, and is basically useless.
* Even if it did work, requiring us to setup and use the confusing `Trie` structure is also unintuitive and verbose.  The parameter should be an `IDictionary<char, string>`

**Comment by caguiclajmg** [comment]
> Apparently the `customRomajiMapping` overwrites the _entire_ mapping

That does indeed sound wrong (coming from a WanaKana perspective), but I believe my original intention was for the user to pass in a `Trie` merged with the standard mapping.

I do acknowledge that it does deviate from what WanaKana's behavior and while my original intent was to create a 1:1 port, calling this a _port_ is probably no longer the direction I want to take.

> * Even if it did work, requiring us to setup and use the confusing `Trie` structure is also unintuitive and verbose.  The parameter should be an `IDictionary<char, string>`

Fair, an overload on `ToRomaji` would probably be a good compromise and additionally an overload on `Trie` to allow merging with an `IReadOnlyDictionary`.

**Comment by caguiclajmg** [comment]
792f45a should address your first point, but then again #5 was already closed so you probably no longer need this.

In any case, I gave your second point a thought but decided against implementing an overload that accepts a `Dictionary`-ish type since `Dictionary` doesn't really make sense as something to merge with a `Trie`.

If you have any other suggestions, feel free to reopen.

**Comment by BlueRaja** [comment]
Another suggestion then:  The `Trie` structure should implement either `IDictionary` or `ISet` _(I don't remember how you're actually using it)_, and then have the method take that interface instead.

It just doesn't make sense for consumers to have to know about and use your custom Trie structure. It's an implementation detail.

**Comment by caguiclajmg** [comment]
A Trie/Prefix Tree is a standard data structure and not some magic container that I came up with overnight, unfortunately .NET doesn't have one so I rolled my own; if you're not familiar with them I suggest reading up about them so you figure out why they don't make sense for me in this case.

The only way a `Dictionary`-ish type would work in this case is if made it like `Dictionary<char, Node>`, but then we circle back to you needing to know about the implementation of a trie node and apparently you don't want that. You can try converting `Node` to something generic, but you'll quickly find out it'll be `Dictionary<char, Dictionary<char, Dictionary<char, ...>>>` (you get the point).

A `Dictionary<char, string>` parameter in `ToRomaji` doesn't make sense since that would mean you're only overwriting the immediate children of the trie's root node. While it would work in your use case since you only wanted to replace ふ which right just below the root node, it's not generic enough to warrant implementation.

I am leaning to a `Dictionary<string, string>` solution, although I haven't given it much thought but it seems it would work. I'll make sure to remember to ping this thread when I decide to do it.

**Comment by BlueRaja** [comment]
Yes, I'm familiar with what a trie is. It's a data structure for fast lookups of strings (or optionally, mapping strings to objects). This means they are fundamentally `ISet<string>` (or `IDictionary<string, T>`).
